import styles from "../styles/Home.module.css";
import React from "react";
import Image from "next/image";
import {
  Box,
  Button,
  Card,
  CardBody,
  CardHeader,
  Container,
  Heading,
  Text
} from "@chakra-ui/react";
import Head from "next/head";
import Footer from "../components/Footer";
import Hero from "../components/Hero";
import DEL from "../public/del-r.png";
import { useRouter } from "next/router";
import NFTGallery from "../components/nftGallery";

export default function Home() {
  const router = useRouter();
  
  return (
    <div>
      <main className={styles.main}>
        <Head>
        <title>DataLink</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        </Head>

        <Container maxW="70%" centerContent>
        {/* DATADAO LOGO */}

        <Box className="logo" display='flex' mt='2' alignItems='center'>
          <Image src={DEL} alt="logo" width={480} height={480} />
        </Box>

        {/* <Text fontSize="4xl" color='black' as='b'>
        Buidling the most accessible Web3 data validation and data-sharing tools.
        </Text> */}

        <br /><br /><br />

        <Text fontSize="6xl" color='green.600' as='b'>
        Learn more about the DEL!
        </Text>

        <br /><br />

        <Button
          bg="green.600"
          color="white"
          colorScheme='green' 
          variant='solid'
          w="25%"
          gap='4'
          mb={4}
          py={12}
          fontSize="3xl"
          alignItems="center"
          justifyContent="center"
          display='flex' mt='2'
          boxShadow='dark-lg' p='8' rounded='xl'
          onClick={() => router.push("/about")}
        >
          Learn More
        </Button>
      </Container>

      </main>
    </div>
  );
}
